blank_issues_enabled: true
contact_links:
  - name: ðŸ¤” Long question or ideas?
    url: https://github.com/MyScriptsobToStartWork/MyScriptsobToStartWork/discussions
    about: Ask long-form questions and discuss ideas.
